version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlfour
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Database!2021"
    ports:
      - "1415:1433"
    volumes:
      - volume1:/var/opt/mssql

volumes:
  volume1:
